### ISSUE TITLE
playback continues after quitting

### ISSUE THREAD

**Issue by czesiekhaker** [cuschk/somafm#7]
This has been annoying me for months now. I tried to fork and fix it but failed due to time constraints and not being that interested in JavaScript.

`mpv` is still running after stopping `somafm` (via `^C`).

### Steps to reproduce

```bash
$ somafm play defcon

  Playing   SomaFM DEF CON Radio
```

Pressing `Ctrl+c` at this point causes the program to output
```bash
  undefined  undefined
```
and the music keeps playing
```bash
$ ps a | grep mpv | grep -v grep
 7421 pts/8    Sl     0:01 mpv -quiet http://ice1.somafm.com/defcon-256-mp3
```

### Workaround

```bash
$ killall mpv
```

This isn't perfect when you have multiple instances of `mpv` running (eg. some clips paused waiting to be finished).

### Version info

```bash
$ somafm --version      
2.1.2
$ mpv --version
mpv 0.23.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.34.101
   libavcodec      57.64.101
   libavformat     57.56.101
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.5-1
```

**Comment by uschek** [comment]
Hi @czesiekhaker,

Thanks for your report!

I can't reproduce this on my machine. Pressing <kbd>ctrl</kbd>+<kbd>c</kbd> or <kbd>q</kbd> or <kbd>esc</kbd> kills the MPlayer or mpv process as expected.

What OS and Node.js version are you using?

You could try the following steps and check if they change anything:

0. Run `$ mpv http://ice1.somafm.com/defcon-256-mp3` directly and press <kbd>ctrl</kbd>+<kbd>c</kbd> to see if the process exits.
1. Install the latest version of Node.js.
2. Install the latest version of mpv.
3. Install [MPlayer](https://mplayerhq.hu). It will be used [by default](https://github.com/uschek/somafm/blob/d52a75ffd38093d6e2271c429b7c3f5a0b3eb472/cli.js#L46-L51) when available.
4. Use a different kill signal by adding a parameter to the [`kill()` function call](https://github.com/uschek/somafm/blob/d52a75ffd38093d6e2271c429b7c3f5a0b3eb472/cli.js#L181). The [default is `SIGTERM`](https://nodejs.org/api/child_process.html#child_process_child_kill_signal), but maybe `SIGINT` or `SIGKILL` works better here (although `SIGKILL` is less friendly).

(I'll fix the `undefined` output in the next release.)

**Comment by cuschk** [comment]
Switched to `execa` and force-killing after a timeout. (17919760b0258300c18999d9c64d6fd6aa101a5c)

This should solve the issue.
